In [3]:
# exercise 1
import numpy as np

def find_the_postion(element, matrix):
    print(set(zip(* np.where(matrix==element))))
    
matrix = np.array([[1,2,3],[1,5,6],[1,8,1]])
find_the_postion(1,matrix)


{(2, 0), (1, 0), (0, 0), (2, 2)}


In [85]:

#ex 2
def pro_lin_mat():
    mat= np.array([[2,3,4],[2,5,6],[1,1,1]])
    return  np.prod(mat,axis=1)

print (pro_lin_mat())

[24 60  1]


In [21]:
#ex 3 

def matrix_compare():
    a= np.array([[2,3,4],[2,3,6],[5,5,5]])
    b=np.array([[2,3,4],[1,70,1],[2,3,4]])
    print(a>=b)

matrix_compare()
    

[[ True  True  True]
 [ True False  True]
 [ True  True  True]]


In [38]:
#ex 4

def val_maxima():
    v=np.array([20,3,20,20,1,3,4,20])
    print(np.where(v==max(v)))
val_maxima()

(array([0, 2, 3, 7], dtype=int64),)


In [195]:
#ex5
"""

"""
def inmultire():
    v=np.array([230, 10, 284, 39, 76])
    while min(v)<100:
        v=np.where(v<100,v*2,v)
    print(v[np.where((v>=100) &(v<=200))])
inmultire()

[160 156 152]


In [77]:
#ex6 
"""
where are sintaxa np.where(conditie,rezultat pentru contidie ==Treu, rezultate pentru conditie==False)
si asta rezolva cam toata problema 
"""
def comparare_vector(a,b):
    return np.where(a>b,a,b)

mat1=np.array([3, 7, 9, 13, -10, 200, 3])
mat2=np.array([4, 5, -9, 100, 300, 230, 1])
print(comparare_vector(mat1,mat2))

[  4   7   9 100 300 230   3]


In [109]:
#ex7 not done yet
import math 
from math import nan

def sumaB(a):
     return np.nansum(a)


def sumaA(a):
    b=a.copy()
    b=np.where(np.isnan(b),0,b)
    return np.sum(b)

def sumaC(a):
    suma=0
    return  np.sum(np.where(np.isnan(a)))
    
mat=np.array([[1,nan,3],[nan,5,6],[7,8,nan]])

%time print(sumaB(mat))
%time print(sumaA(mat))
%time print(sumaC(mat))

30.0
Wall time: 0 ns
30.0
Wall time: 0 ns
6
Wall time: 197 ms


In [183]:
#ex8 not done yet 
def nan_index(mat):
    print(set(zip(*np.where(np.isnan(mat[:,0:4])))))
    
data = np.genfromtxt("iris.txt",delimiter=",")
data.itemset((4,4),nan)
print(data)
nan_index(data)

[[5.1 3.5 1.4 0.2 nan]
 [4.9 3.  1.4 0.2 nan]
 [4.7 3.2 1.3 0.2 nan]
 [4.6 3.1 1.5 0.2 nan]
 [5.  3.6 1.4 0.2 nan]
 [5.4 3.9 1.7 0.4 nan]
 [4.6 3.4 1.4 0.3 nan]
 [5.  3.4 1.5 0.2 nan]
 [4.4 2.9 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.4 3.7 1.5 0.2 nan]
 [4.8 3.4 1.6 0.2 nan]
 [4.8 3.  1.4 0.1 nan]
 [4.3 3.  1.1 0.1 nan]
 [5.8 4.  1.2 0.2 nan]
 [5.7 4.4 1.5 0.4 nan]
 [5.4 3.9 1.3 0.4 nan]
 [5.1 3.5 1.4 0.3 nan]
 [5.7 3.8 1.7 0.3 nan]
 [5.1 3.8 1.5 0.3 nan]
 [5.4 3.4 1.7 0.2 nan]
 [5.1 3.7 1.5 0.4 nan]
 [4.6 3.6 1.  0.2 nan]
 [5.1 3.3 1.7 0.5 nan]
 [4.8 3.4 1.9 0.2 nan]
 [5.  3.  1.6 0.2 nan]
 [5.  3.4 1.6 0.4 nan]
 [5.2 3.5 1.5 0.2 nan]
 [5.2 3.4 1.4 0.2 nan]
 [4.7 3.2 1.6 0.2 nan]
 [4.8 3.1 1.6 0.2 nan]
 [5.4 3.4 1.5 0.4 nan]
 [5.2 4.1 1.5 0.1 nan]
 [5.5 4.2 1.4 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [5.  3.2 1.2 0.2 nan]
 [5.5 3.5 1.3 0.2 nan]
 [4.9 3.1 1.5 0.1 nan]
 [4.4 3.  1.3 0.2 nan]
 [5.1 3.4 1.5 0.2 nan]
 [5.  3.5 1.3 0.3 nan]
 [4.5 2.3 1.3 0.3 nan]
 [4.4 3.2 1.3 0.2 nan]
 [5.  3.5 1

In [235]:
# exe 9
"""
zip pentru a crea tuple cu indexul linie coloana a elemetelor ce respecta conditia 
"""
def functie_9(mat,lmin,lmax):
    return set(zip(*np.where((mat >=lmin)&(mat<=lmax))))
    
mat =np.array([[1,2,3],[23,45,63],[7,8,9]])
functie_9(mat,1,10)

{(0, 0), (0, 1), (0, 2), (2, 0), (2, 1), (2, 2)}

In [230]:
#exe 10
"""
folosim zip pentru a face un tuple cu indexul si elemetul cautat
iar in urma lui arg sort se creaza o lista de indexsi sortata
"""
def functie_10(vect,k):
    return set(zip(np.argsort(vect)[-k:],vect[np.argsort(vect)[-k:]]))
               
vect=np.array([1,2,34,45,34,9,10,24,30])
print(functie_10(vect,4))


{(8, 30), (4, 34), (3, 45), (2, 34)}
