In [5]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.linear_model import Lasso
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import GridSearchCV , RandomizedSearchCV

In [9]:
breastC=pd.read_csv("breastC.csv",header=None)
breastC.head()

0      1      2       3       4        5       6       7        8       9   \
0   5  18.02  27.60  117.50  1013.0  0.09489  0.1036  0.1086  0.07055  0.1865   
1   2  17.99  10.38  122.80  1001.0  0.11840  0.2776  0.3001  0.14710  0.2419   
2   0  21.37  17.44  137.50  1373.0  0.08836  0.1189  0.1255  0.08180  0.2333   
3   0  11.42  20.38   77.58   386.1  0.14250  0.2839  0.2414  0.10520  0.2597   
4   0  20.29  14.34  135.10  1297.0  0.10030  0.1328  0.1980  0.10430  0.1809   

  ...       23      24      25      26      27      28      29       30   31  \
0 ...   139.70  1436.0  0.1195  0.1926  0.3140  0.1170  0.2677  0.08113  5.0   
1 ...   184.60  2019.0  0.1622  0.6656  0.7119  0.2654  0.4601  0.11890  3.0   
2 ...   159.10  1949.0  0.1188  0.3449  0.3414  0.2032  0.4334  0.09067  2.5   
3 ...    98.87   567.7  0.2098  0.8663  0.6869  0.2575  0.6638  0.17300  2.0   
4 ...   152.20  1575.0  0.1374  0.2050  0.4000  0.1625  0.2364  0.07678  3.5   

    32  
0   31  
1   61  
2  116  
3  123  
4   27  

[5 rows x 33 columns]

In [49]:
machine=pd.read_csv("machine.csv",header=None)

machine_values=machine.values
machine_values=machine_values[:,2:9]
print(machine_values)
machine.head()

[[125 256 6000 ... 16 128 198]
 [29 8000 32000 ... 8 32 269]
 [29 8000 32000 ... 8 32 220]
 ...
 [125 2000 8000 ... 2 14 52]
 [480 512 8000 ... 0 0 67]
 [480 1000 4000 ... 0 0 45]]


0        1    2     3      4    5   6    7    8    9
0  adviser    32/60  125   256   6000  256  16  128  198  199
1   amdahl   470v/7   29  8000  32000   32   8   32  269  253
2   amdahl  470v/7a   29  8000  32000   32   8   32  220  253
3   amdahl  470v/7b   29  8000  32000   32   8   32  172  253
4   amdahl  470v/7c   29  8000  16000   32   8   16  132  132

In [127]:
communities=pd.read_csv("communities.csv",header=None)
coloana=[0,1,2,3,4,113,114,115,116,117,121,122,123,124,126]
communities.drop(communities.columns[coloana],axis=1,inplace=True)
print(col)
communities.drop(communities=='?',inplace=True)
communities.head()

Int64Index([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
            ...
            108, 109, 110, 111, 112, 118, 119, 120, 125, 127],
           dtype='int64', length=113)


5     6     7     8     9     10    11    12    13    14   ...    108  \
0  0.19  0.33  0.02  0.90  0.12  0.17  0.34  0.47  0.29  0.32  ...   0.13   
1  0.00  0.16  0.12  0.74  0.45  0.07  0.26  0.59  0.35  0.27  ...      ?   
2  0.00  0.42  0.49  0.56  0.17  0.04  0.39  0.47  0.28  0.32  ...      ?   
3  0.04  0.77  1.00  0.08  0.12  0.10  0.51  0.50  0.34  0.21  ...      ?   
4  0.01  0.55  0.02  0.95  0.09  0.05  0.38  0.38  0.23  0.36  ...      ?   

    109   110   111   112   118   119   120   125   127  
0  0.94  0.93  0.03  0.07  0.12  0.26  0.20  0.32  0.20  
1     ?     ?     ?     ?  0.02  0.12  0.45  0.00  0.67  
2     ?     ?     ?     ?  0.01  0.21  0.02  0.00  0.43  
3     ?     ?     ?     ?  0.02  0.39  0.28  0.00  0.12  
4     ?     ?     ?     ?  0.04  0.09  0.02  0.00  0.03  

[5 rows x 113 columns]

In [43]:
housing=pd.read_csv("housing.csv",delimiter='\s+',header=None)
housing.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2